# Generated by Django 4.2.30 on 2026-06-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Foggy', 'Foggy'), ('Windy', 'Windy'), ('Storm', 'Storm'), ('Flooding', 'Flooding'), ('Snow', 'Snow'), ('Extreme Heat', 'Extreme Heat')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visibility', models.CharField(default='Good', max_length=50)),
                ('wind_condition', models.CharField(default='Calm', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='weather_photos/')),
                ('reporter_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('reporter_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='locations.location')),
            ],
        ),
    ]
