# Generated by Django 4.2.30 on 2026-06-17 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followed_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
